const MATCHES_COUNT = 150;
const USERS_COUNT = 50;
const ITEMS_COUNT = 20;
const FOLLOWINGS_COUNT = 300;
const ONGOING_MATCHES_COUNT = 5;
const INVITES_COUNT = 10;

module.exports = {
  USERS_COUNT,
  MATCHES_COUNT,
  ITEMS_COUNT,
  FOLLOWINGS_COUNT,
  ONGOING_MATCHES_COUNT,
  INVITES_COUNT,
};
